name: GitHub_Actions
on:
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - run: |
          python -m pip install --upgrade pip
          sudo apt install tesseract-ocr libtesseract-dev tesseract-ocr-jpn
          pip install pyocr
          pip install tesseract
          python test2.py
